import type { HarnessSettingsMap } from "./SettingsSchema";

/** Default per-invocation timeout (ms) used when neither config nor harness.config.json define one. */
export const DEFAULT_PHASE_TIMEOUT_MS = 3_600_000; // 60 minutes
export const DEFAULT_WAIT_TIMEOUT_MS = 60_000; // 60 seconds

export const DEFAULT_SETTINGS: HarnessSettingsMap = {
  claude: {
    timeoutMs: DEFAULT_PHASE_TIMEOUT_MS,
    phases: {
      bootstrap: { model: "claude-haiku-5-5", effort: "high" },
      planning: { model: "claude-opus-5-5", effort: "medium" },
      refinement_questions: { model: "claude-sonnet-5-5", effort: "low" },
      refinement_consolidation: { model: "claude-sonnet-5-5", effort: "low" },
      implementation: { model: "claude-haiku-5-5", effort: "high" },
      review_tl: { model: "claude-opus-5-5", effort: "low" },
      review_adv: { model: "claude-opus-5-5", effort: "low" },
      memory: { model: "claude-haiku-5-5", effort: "high" },
      deploy_message: { model: "claude-haiku-5-5", effort: "medium" },
      diagnose: { model: "claude-haiku-5-5", effort: "high" },
      qa_planning: { model: "claude-haiku-5-5", effort: "high" },
      qa_analysis: { model: "claude-haiku-5-5", effort: "high" },
      qa_reporting: { model: "claude-haiku-5-5", effort: "medium" },
    },
  },
  antigravity: {
    timeoutMs: DEFAULT_PHASE_TIMEOUT_MS,
    phases: {
      bootstrap: { model: "gemini-3.8-flash", effort: "medium" },
      planning: { model: "gemini-3.8-flash", effort: "high" },
      refinement_questions: { model: "gemini-3.8-flash", effort: "low" },
      refinement_consolidation: { model: "gemini-3.8-flash", effort: "low" },
      implementation: { model: "gemini-3.8-flash", effort: "medium" },
      review_tl: { model: "gemini-3.8-flash", effort: "low" },
      review_adv: { model: "gemini-3.8-flash", effort: "low" },
      memory: { model: "gemini-3.8-flash", effort: "low" },
      deploy_message: { model: "gemini-3.8-flash", effort: "low" },
      diagnose: { model: "gemini-3.8-flash", effort: "low" },
      qa_planning: { model: "gemini-3.8-flash", effort: "medium" },
      qa_analysis: { model: "gemini-3.8-flash", effort: "medium" },
      qa_reporting: { model: "gemini-3.8-flash", effort: "low" },
    },
  },
  copilot: {
    timeoutMs: DEFAULT_PHASE_TIMEOUT_MS,
    phases: {
      bootstrap: { model: "gpt-6-luna", effort: "xhigh" },
      planning: { model: "gpt-6.1-sol", effort: "medium" },
      refinement_questions: { model: "gpt-6.1-sol", effort: "low" },
      refinement_consolidation: { model: "gpt-6.1-sol", effort: "low" },
      implementation: { model: "gpt-6-luna", effort: "xhigh" },
      review_tl: { model: "gpt-6.1-sol", effort: "low" },
      review_adv: { model: "gpt-6.1-sol", effort: "low" },
      memory: { model: "gpt-6-luna", effort: "xhigh" },
      deploy_message: { model: "gpt-6-luna", effort: "xhigh" },
      diagnose: { model: "gpt-6-luna", effort: "xhigh" },
      qa_planning: { model: "gpt-6-luna", effort: "xhigh" },
      qa_analysis: { model: "gpt-6-luna", effort: "xhigh" },
      qa_reporting: { model: "gpt-6-luna", effort: "xhigh" },
    },
  },
  cursor: {
    timeoutMs: DEFAULT_PHASE_TIMEOUT_MS,
    phases: {
      bootstrap: { model: "claude-haiku-5-5", effort: "high" },
      planning: { model: "claude-opus-5-5", effort: "medium" },
      refinement_questions: { model: "claude-sonnet-5-5", effort: "low" },
      refinement_consolidation: { model: "claude-sonnet-5-5", effort: "low" },
      implementation: { model: "claude-haiku-5-5", effort: "high" },
      review_tl: { model: "claude-opus-5-5", effort: "low" },
      review_adv: { model: "claude-opus-5-5", effort: "low" },
      memory: { model: "claude-haiku-5-5", effort: "high" },
      deploy_message: { model: "claude-haiku-5-5", effort: "medium" },
      diagnose: { model: "claude-haiku-5-5", effort: "high" },
      qa_planning: { model: "claude-haiku-5-5", effort: "high" },
      qa_analysis: { model: "claude-haiku-5-5", effort: "high" },
      qa_reporting: { model: "claude-haiku-5-5", effort: "medium" },
    },
  },
  codex: {
    timeoutMs: DEFAULT_PHASE_TIMEOUT_MS,
    phases: {
      bootstrap: { model: "gpt-6-luna", effort: "xhigh" },
      planning: { model: "gpt-6.1-sol", effort: "medium" },
      refinement_questions: { model: "gpt-6.1-sol", effort: "low" },
      refinement_consolidation: { model: "gpt-6.1-sol", effort: "low" },
      implementation: { model: "gpt-6-luna", effort: "xhigh" },
      review_tl: { model: "gpt-6.1-sol", effort: "low" },
      review_adv: { model: "gpt-6.1-sol", effort: "low" },
      memory: { model: "gpt-6-luna", effort: "xhigh" },
      deploy_message: { model: "gpt-6-luna", effort: "xhigh" },
      diagnose: { model: "gpt-6-luna", effort: "xhigh" },
      qa_planning: { model: "gpt-6-luna", effort: "xhigh" },
      qa_analysis: { model: "gpt-6-luna", effort: "xhigh" },
      qa_reporting: { model: "gpt-6-luna", effort: "xhigh" },
    },
  },
};
