import os from 'node:os'
import { AntigravityCLIErase } from '../../agent-runner/antigravity-cli/AntigravityCLIErase'
import { ClaudeCLIErase } from '../../agent-runner/claude-cli/ClaudeCLIErase'
import { CodexCLIErase } from '../../agent-runner/codex-cli/CodexCLIErase'
import { CopilotCLIErase } from '../../agent-runner/copilot-cli/CopilotCLIErase'
import { CLIEraseRegistry } from '../../agent-runner/erase/CLIEraseRegistry'
import { OpenCodeCLIErase } from '../../agent-runner/opencode-cli/OpenCodeCLIErase'
import type {
  EraseEnvironment,
  ErasePreview,
  EraseResult,
  EraseTarget,
  ProjectHistoryErasePort,
} from '../../agent-runner/erase/types'

const TARGETS: readonly { name: string; value: EraseTarget }[] = Object.freeze([
  { name: 'Claude Code', value: 'claude-code' },
  { name: 'Codex', value: 'codex' },
  { name: 'Copilot', value: 'copilot' },
  { name: 'Antigravity', value: 'antigravity' },
  { name: 'OpenCode', value: 'opencode' },
])

export class ProjectHistoryEraseService implements ProjectHistoryErasePort {
  constructor(private readonly registry: CLIEraseRegistry) {}

  discover(target: EraseTarget): Promise<ErasePreview> {
    return this.registry.get(target).discover()
  }

  erase(preview: ErasePreview): Promise<EraseResult> {
    return this.registry.get(preview.target).erase(preview)
  }
}

export interface EraseCommandDependencies {
  readonly service: ProjectHistoryErasePort
  readonly selectTarget: () => Promise<EraseTarget>
  readonly confirm: (preview: ErasePreview) => Promise<boolean>
  readonly write: (message: string) => void
  readonly setExitCode: (code: number) => void
}

const ERASE_BANNER = `
┌─────────────────────────────────────────────────────────────────┐
│  hrns erase — Agent Runner History Cleaner                      │
│                                                                 │
│  Removes project-specific data generated by AI agent CLIs:     │
│  cache, memory, session history, projects, and similar files.   │
│  Credentials, config, extensions, and tools are preserved.     │
│                                                                 │
│  A deletion preview is shown before any file is removed.       │
│  Confirmation is required and defaults to NO.                  │
└─────────────────────────────────────────────────────────────────┘
`

export async function cmdErase(args: readonly string[] = [], provided?: EraseCommandDependencies): Promise<EraseResult> {
  const dependencies = provided ?? await defaultDependencies()
  dependencies.write(ERASE_BANNER)
  const requestedTarget = parseTarget(args)
  const target = requestedTarget ?? await dependencies.selectTarget()
  const preview = await dependencies.service.discover(target)

  if (!preview.entries.length) {
    dependencies.write(`Nothing to erase for ${target}. Missing mappings: ${preview.missing.length}.`)
    return { status: 'noop', deleted: [], skipped: [], failed: [] }
  }

  dependencies.write(renderPreview(preview))
  let accepted = false
  try {
    accepted = await dependencies.confirm(preview)
  } catch (error) {
    if ((error as Error).name !== 'ExitPromptError') throw error
  }
  if (!accepted) {
    dependencies.write(`Project history erasure cancelled for ${target}.`)
    return { status: 'cancelled', deleted: [], skipped: [], failed: [] }
  }

  const result = await dependencies.service.erase(preview)
  if (result.status === 'partial') {
    dependencies.write(`Project history erasure partially failed for ${target}.`)
    for (const failure of result.failed) dependencies.write(`${failure.path} [${failure.code}]`)
    dependencies.setExitCode(1)
  } else {
    dependencies.write(`Project history erased for ${target}: ${result.deleted.length} deleted, ${result.skipped.length} skipped.`)
  }
  return result
}

function renderPreview(preview: ErasePreview): string {
  const lines = preview.entries.map(entry => `  ${entry.path} (${entry.kind}, ${entry.bytes} bytes)`)
  return [`Erase preview ${preview.planId} for ${preview.target}:`, ...lines].join('\n')
}

function parseTarget(args: readonly string[]): EraseTarget | undefined {
  const index = args.indexOf('--target')
  if (index < 0) return undefined
  const value = args[index + 1]
  if (!TARGETS.some(target => target.value === value)) throw new Error(`Unsupported erase target: ${value ?? ''}`)
  return value as EraseTarget
}

async function defaultDependencies(): Promise<EraseCommandDependencies> {
  const environment: EraseEnvironment = { platform: process.platform, homeDir: os.homedir(), variables: { ...process.env } }
  const registry = new CLIEraseRegistry()
    .register('claude-code', new ClaudeCLIErase(environment))
    .register('codex', new CodexCLIErase(environment))
    .register('copilot', new CopilotCLIErase(environment))
    .register('antigravity', new AntigravityCLIErase(environment))
    .register('opencode', new OpenCodeCLIErase(environment))
  const prompts = await import('@inquirer/prompts')
  return {
    service: new ProjectHistoryEraseService(registry),
    selectTarget: () => prompts.select({ message: 'Select agent history to erase', choices: [...TARGETS] }),
    confirm: () => prompts.confirm({ message: 'Erase every path shown above?', default: false }),
    write: message => console.log(message),
    setExitCode: code => { process.exitCode = code },
  }
}
